package data.entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblCustomer generated by hbm2java
 */
@Entity
@Table(name = "tbl_customer", catalog = "HotelDB")
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String customerId;
	private String password;
	private String firstName;
	private String lastName;
	private String address;
	private String postalCode;
	private String country;
	private String email;
	private String phone;
	private String imageLink;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Customer() {
	}

	public Customer(String customerId, String password, String firstName, String lastName, String address,
			String postalCode, String country, String email, String phone) {
		this.customerId = customerId;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.postalCode = postalCode;
		this.country = country;
		this.email = email;
		this.phone = phone;
	}

	public Customer(String customerId, String password, String firstName, String lastName, String address,
			String postalCode, String country, String email, String phone, String imageLink,
			Set<Booking> bookings) {
		this.customerId = customerId;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.postalCode = postalCode;
		this.country = country;
		this.email = email;
		this.phone = phone;
		this.imageLink = imageLink;
		this.bookings = bookings;
	}

	@Id

	@Column(name = "customerID", unique = true, nullable = false, length = 50)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstName", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "postalCode", nullable = false, length = 50)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "country", nullable = false, length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "imageLink", length = 256)
	public String getImageLink() {
		return this.imageLink;
	}

	public void setImageLink(String imageLink) {
		this.imageLink = imageLink;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tblCustomer")
	public Set<Booking> getTblBookings() {
		return this.bookings;
	}

	public void setTblBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
