package data.entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblRoomType generated by hbm2java
 */
@Entity
@Table(name = "tbl_room_type", catalog = "HotelDB")
public class RoomType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer typeId;
	private String name;
	private double pricePerNight;
	private int singleBedAmount;
	private int doubleBedAmount;
	private int numberOfWindow;
	private int capacity;
	private String imageLink;
	private Set<BookingDetails> tblBookingDetailses = new HashSet<BookingDetails>(0);
	private Set<Service> services = new HashSet<Service>(0);
	private Set<Room> rooms = new HashSet<Room>(0);

	public RoomType() {
	}

	public RoomType(String name, double pricePerNight, int singleBedAmount, int doubleBedAmount, int numberOfWindow,
			int capacity, String imageLink) {
		this.name = name;
		this.pricePerNight = pricePerNight;
		this.singleBedAmount = singleBedAmount;
		this.doubleBedAmount = doubleBedAmount;
		this.numberOfWindow = numberOfWindow;
		this.capacity = capacity;
		this.imageLink = imageLink;
	}

	public RoomType(String name, double pricePerNight, int singleBedAmount, int doubleBedAmount, int numberOfWindow,
			int capacity, String imageLink, Set<BookingDetails> tblBookingDetailses, Set<Service> services,
			Set<Room> rooms) {
		this.name = name;
		this.pricePerNight = pricePerNight;
		this.singleBedAmount = singleBedAmount;
		this.doubleBedAmount = doubleBedAmount;
		this.numberOfWindow = numberOfWindow;
		this.capacity = capacity;
		this.imageLink = imageLink;
		this.tblBookingDetailses = tblBookingDetailses;
		this.services = services;
		this.rooms = rooms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeID", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pricePerNight", nullable = false, precision = 22, scale = 0)
	public double getPricePerNight() {
		return this.pricePerNight;
	}

	public void setPricePerNight(double pricePerNight) {
		this.pricePerNight = pricePerNight;
	}

	@Column(name = "singleBedAmount", nullable = false)
	public int getSingleBedAmount() {
		return this.singleBedAmount;
	}

	public void setSingleBedAmount(int singleBedAmount) {
		this.singleBedAmount = singleBedAmount;
	}

	@Column(name = "doubleBedAmount", nullable = false)
	public int getDoubleBedAmount() {
		return this.doubleBedAmount;
	}

	public void setDoubleBedAmount(int doubleBedAmount) {
		this.doubleBedAmount = doubleBedAmount;
	}

	@Column(name = "numberOfWindow", nullable = false)
	public int getNumberOfWindow() {
		return this.numberOfWindow;
	}

	public void setNumberOfWindow(int numberOfWindow) {
		this.numberOfWindow = numberOfWindow;
	}

	@Column(name = "capacity", nullable = false)
	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	@Column(name = "imageLink", nullable = false, length = 256)
	public String getImageLink() {
		return this.imageLink;
	}

	public void setImageLink(String imageLink) {
		this.imageLink = imageLink;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tblRoomType")
	public Set<BookingDetails> getTblBookingDetailses() {
		return this.tblBookingDetailses;
	}

	public void setTblBookingDetailses(Set<BookingDetails> tblBookingDetailses) {
		this.tblBookingDetailses = tblBookingDetailses;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "tbl_room_service", catalog = "HotelDB", joinColumns = {
			@JoinColumn(name = "roomType", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "roomService", nullable = false, updatable = false) })
	public Set<Service> getTblServices() {
		return this.services;
	}

	public void setTblServices(Set<Service> services) {
		this.services = services;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tblRoomType")
	public Set<Room> getTblRooms() {
		return this.rooms;
	}

	public void setTblRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}

}
