package data.entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * TblService generated by hbm2java
 */
@Entity
@Table(name = "tbl_service", catalog = "HotelDB")
public class Service implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer serviceId;
	private String serviceName;
	private String description;
	private Set<RoomType> roomTypes = new HashSet<RoomType>(0);

	public Service() {
	}

	public Service(String serviceName, String description) {
		this.serviceName = serviceName;
		this.description = description;
	}

	public Service(String serviceName, String description, Set<RoomType> roomTypes) {
		this.serviceName = serviceName;
		this.description = description;
		this.roomTypes = roomTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "serviceID", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "serviceName", nullable = false, length = 100)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "tbl_room_service", catalog = "HotelDB", joinColumns = {
			@JoinColumn(name = "roomService", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "roomType", nullable = false, updatable = false) })
	public Set<RoomType> getTblRoomTypes() {
		return this.roomTypes;
	}

	public void setTblRoomTypes(Set<RoomType> roomTypes) {
		this.roomTypes = roomTypes;
	}

}
