package entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBooking generated by hbm2java
 */
@Entity
@Table(name = "tbl_booking", catalog = "HotelDB")
public class Booking implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer bookingId;
	private Customer customer;
	private int adult;
	private int child;
	private Date arrivalDay;
	private Date checkOutDay;
	private Date bookingDay;
	private String comment;
	private Set<BookingDetails> tblBookingDetailses = new HashSet<BookingDetails>(0);
	private Payment payment;

	public Booking() {
	}

	public Booking(Customer customer, int adult, int child, Date arrivalDay, Date checkOutDay, Date bookingDay, String comment) {
		this.customer = customer;
		this.adult = adult;
		this.child = child;
		this.arrivalDay = arrivalDay;
		this.checkOutDay = checkOutDay;
		this.bookingDay = bookingDay;
		this.comment = comment;
	}

	public Booking(Customer customer, int adult, int child, Date arrivalDay, Date checkOutDay, Date bookingDay, String comment,
			Set<BookingDetails> tblBookingDetailses, Payment payment) {
		this.customer = customer;
		this.adult = adult;
		this.child = child;
		this.arrivalDay = arrivalDay;
		this.checkOutDay = checkOutDay;
		this.bookingDay = bookingDay;
		this.comment = comment;
		this.tblBookingDetailses = tblBookingDetailses;
		this.payment = payment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bookingID", unique = true, nullable = false)
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customerID", nullable = false)
	public Customer getTblCustomer() {
		return this.customer;
	}

	public void setTblCustomer(Customer customer) {
		this.customer = customer;
	}
	
	@Column(name = "adult", nullable = false)
	public int getAdult() {
		return this.adult;
	}

	public void setAdult(int adult) {
		this.adult = adult;
	}
	
	@Column(name = "child", nullable = false)
	public int getChild() {
		return this.child;
	}

	public void setChild(int child) {
		this.child = child;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrivalDay", nullable = false, length = 19)
	public Date getArrivalDay() {
		return this.arrivalDay;
	}

	public void setArrivalDay(Date arrivalDay) {
		this.arrivalDay = arrivalDay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checkOutDay", nullable = false, length = 19)
	public Date getCheckOutDay() {
		return this.checkOutDay;
	}

	public void setCheckOutDay(Date checkOutDay) {
		this.checkOutDay = checkOutDay;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookingDay", nullable = false, length = 19)
	public Date getBookingDay() {
		return this.bookingDay;
	}

	public void setBookingDay(Date bookingDay) {
		this.bookingDay = bookingDay;
	}

	@Column(name = "comment", nullable = false, length = 300)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tblBooking")
	public Set<BookingDetails> getTblBookingDetailses() {
		return this.tblBookingDetailses;
	}

	public void setTblBookingDetailses(Set<BookingDetails> tblBookingDetailses) {
		this.tblBookingDetailses = tblBookingDetailses;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "tblBooking")
	public Payment getTblPayment() {
		return this.payment;
	}

	public void setTblPayment(Payment payment) {
		this.payment = payment;
	}

}
