package entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblPaymentType generated by hbm2java
 */
@Entity
@Table(name = "tbl_payment_type", catalog = "HotelDB")
public class PaymentType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String type;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public PaymentType() {
	}

	public PaymentType(String type) {
		this.type = type;
	}

	public PaymentType(String type, Set<Payment> payments) {
		this.type = type;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tblPaymentType")
	public Set<Payment> getTblPayments() {
		return this.payments;
	}

	public void setTblPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
