package entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblRoom generated by hbm2java
 */
@Entity
@Table(name = "tbl_room", catalog = "HotelDB")
public class Room implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int roomId;
	private RoomType roomType;
	private boolean isAvailable;

	public Room() {
	}

	public Room(int roomId, RoomType roomType, boolean isAvailable) {
		this.roomId = roomId;
		this.roomType = roomType;
		this.isAvailable = isAvailable;
	}

	@Id
	@Column(name = "roomID", unique = true, nullable = false)
	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "roomType", nullable = false)
	public RoomType getTblRoomType() {
		return this.roomType;
	}

	public void setTblRoomType(RoomType roomType) {
		this.roomType = roomType;
	}

	@Column(name = "isAvailable", nullable = false)
	public boolean isIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

}
