package entity;
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblBookingDetailsId generated by hbm2java
 */
@Embeddable
public class TblBookingDetailsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int bookingId;
	private int roomType;

	public TblBookingDetailsId() {
	}

	public TblBookingDetailsId(int bookingId, int roomType) {
		this.bookingId = bookingId;
		this.roomType = roomType;
	}

	@Column(name = "bookingID", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "roomType", nullable = false)
	public int getRoomType() {
		return this.roomType;
	}

	public void setRoomType(int roomType) {
		this.roomType = roomType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblBookingDetailsId))
			return false;
		TblBookingDetailsId castOther = (TblBookingDetailsId) other;

		return (this.getBookingId() == castOther.getBookingId()) && (this.getRoomType() == castOther.getRoomType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookingId();
		result = 37 * result + this.getRoomType();
		return result;
	}

}
