package phuc.entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblBookingDetails generated by hbm2java
 */
@Entity
@Table(name = "tbl_booking_details", catalog = "HotelDB")
public class BookingDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblBookingDetailsId id;
	private Booking booking;
	private RoomType roomType;
	private int amount;

	public BookingDetails() {
	}

	public BookingDetails(TblBookingDetailsId id, Booking booking, RoomType roomType, int amount) {
		this.id = id;
		this.booking = booking;
		this.roomType = roomType;
		this.amount = amount;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookingId", column = @Column(name = "bookingID", nullable = false)),
			@AttributeOverride(name = "roomType", column = @Column(name = "roomType", nullable = false)) })
	public TblBookingDetailsId getId() {
		return this.id;
	}

	public void setId(TblBookingDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "bookingID", nullable = false, insertable = false, updatable = false)
	public Booking getTblBooking() {
		return this.booking;
	}

	public void setTblBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "roomType", nullable = false, insertable = false, updatable = false)
	public RoomType getTblRoomType() {
		return this.roomType;
	}

	public void setTblRoomType(RoomType roomType) {
		this.roomType = roomType;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

}
