package phuc.entity;
// default package
// Generated Oct 7, 2017 4:34:54 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblPayment generated by hbm2java
 */
@Entity
@Table(name = "tbl_payment", catalog = "HotelDB")
public class Payment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int bookingId;
	private Booking booking;
	private PaymentType paymentType;
	private Date payTime;
	private double amount;
	private double paid;

	public Payment() {
	}

	public Payment(Booking booking, PaymentType paymentType, Date payTime, double amount, double paid) {
		this.booking = booking;
		this.paymentType = paymentType;
		this.payTime = payTime;
		this.amount = amount;
		this.paid = paid;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tblBooking"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "bookingID", unique = true, nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public Booking getTblBooking() {
		return this.booking;
	}

	public void setTblBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "paymentType", nullable = false)
	public PaymentType getTblPaymentType() {
		return this.paymentType;
	}

	public void setTblPaymentType(PaymentType paymentType) {
		this.paymentType = paymentType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payTime", nullable = false, length = 19)
	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	@Column(name = "amount", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "paid", nullable = false, precision = 22, scale = 0)
	public double getPaid() {
		return this.paid;
	}

	public void setPaid(double paid) {
		this.paid = paid;
	}

}
